"""Init

Revision ID: 7cb24ef3fb8d
Revises: 233aa49bc990
Create Date: 2023-02-21 17:28:17.787838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb24ef3fb8d'
down_revision = '233aa49bc990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
