"""Revised job table

Revision ID: d48894676926
Revises: d7efa1a392cc
Create Date: 2023-02-22 19:13:09.679805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48894676926'
down_revision = 'd7efa1a392cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('lead', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead'], ['Employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Job_id'), 'Job', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Job_id'), table_name='Job')
    op.drop_table('Job')
    # ### end Alembic commands ###
