"""Added initial job table

Revision ID: d7efa1a392cc
Revises: 7cb24ef3fb8d
Create Date: 2023-02-22 19:08:51.380144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7efa1a392cc'
down_revision = '7cb24ef3fb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
